### ISSUE TITLE
when ever i try to access http site it shows 403 

### ISSUE THREAD

**Issue by Touseef993** [grgk/seo-analyzer#3]
I am using grgk analyzer in my project for mostly https sites it works fine but when ever i try to search http site only its show 403 error or undefined variable results i know the results were not there but why cant we analyze the http sites

Error loading page: Error getting url: Client error: `GET https://iberianodonataucm.myspecies.info/` resulted in a `403 Forbidden` response:
Forbidden (truncated...)

![image](https://user-images.githubusercontent.com/45680294/61946222-6a610880-afbb-11e9-8147-eb2c44684c0d.png)

**Comment by grgk** [comment]
Hi, I'm not sure if I understood your problem well, but the URL you've provided above simply returns 403 Forbiden response, so it can't be loaded and analyzed. If you still have a problem please come back with a more detailed description.

**Comment by Touseef993** [comment]
Hi, ok maybe that is the case but cant we find data realted to http sites because i have tried 7 to 8 http sites and it cant just find results can you help me in this regard please thankyou
for testing purpose's i have tried these site Note(Some of them are now on Https so we will get there results) http://scratchpads.eu/explore/sites-list

**Comment by grgk** [comment]
@Touseef993, please try the latest version from tag 1.0.4 and let me know if it helped.

**Comment by Touseef993** [comment]
@grgk Thankyou updating package fixed the issue.

**Comment by Touseef993** [comment]
@grgk  hi hope you are doing well,
 in testing procedure i found that some sites return 406 Not-acceptable 
can you please help me in this regard.

**Comment by grgk** [comment]
@Touseef993 could you give some examples? Thanks

**Comment by Touseef993** [comment]
@grgk sure, let me share some website's i tried to crawl,
hotmail.com, udemy.com, fliwheel.com, reddit.com
some still returns 403 forbidden response,
while others are 
406 not acceptable response,
401 unauthorized response,
And one more thing sometimes it shows perfect result for hotmail.com while sometime is shows 403.

**Comment by grgk** [comment]
hotmail.com - simply redirects to outlook.live.com, and it works fine then,
udemy.com - looks they have some bot detecting solution and doesn't allow to read by bots,
fliwheel.com - works fine,
reddit.com - can't reproduce, it works fine for me.
I think you could simply implement error catching and take some action when it happened. You never know if a given host will answer or not.

**Comment by Touseef993** [comment]
@grgk  thanks for your quick response, sorry try fliwheel.co
i think i need to pass the domain names instead of a url maybe that is what causing the issue,
and yes i m catching the errors for now but you never know what the user is going to input 
thanks for your quick response once again i m in love with this package..!

**Comment by grgk** [comment]
@Touseef993 please try the version 1.0.5. Should help with the 406 errors.
